/* autogenerated by Processing revision 1304 on 2026-01-28 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.sound.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class ghosdo extends PApplet {



PImage stopR;
PImage stopL;
PImage dash1R;
PImage dash1L;
PImage dash2R;
PImage dash2L;
PImage dash3R;
PImage dash3L;
PImage dash4R;
PImage dash4L;
PImage jumpR;
PImage jumpL;
PImage fireR;
PImage fireL;
PImage itemS;
PImage itemM;
PImage itemL;
PImage enemySR;
PImage enemySL;
PImage enemyLR;
PImage enemyLL;
PImage beamR;
PImage beamL;
PImage Get;
PImage damage;
PImage hit;
PImage begin;
PImage ready;
PImage go;
PImage win;
PImage lose;

SoundFile dash_SE;
SoundFile jump_SE;
SoundFile land_SE;
SoundFile fire_SE;
SoundFile get_SE;
SoundFile damage_SE;
SoundFile hit_SE;
SoundFile pinch_SE;
SoundFile ready_SE;
SoundFile go_SE;
SoundFile win_SE;
SoundFile lose_SE;

float player_width=35;
float player_height=70;
float player_dash=0.3f;
float player_ax=1200;
float player_ay=2400;
float player_vxMax=400;
float player_vyMax=1200;
int player_hpMax=100;
int player_hpAbsorb=1;
int player_satietyMax=10;

int item_number=25;
float itemS_rate=3;
float itemM_rate=2;
float itemL_rate=1;

float itemS_width=40;
float itemS_height=40;
float itemS_v=160;
int itemS_point=1;

float itemM_width=60;
float itemM_height=60;
float itemM_v=240;
int itemM_point=3;

float itemL_width=80;
float itemL_height=80;
float itemL_v=320;
int itemL_point=5;

int enemy_number=25;
int enemyS_rate=3;
int enemyL_rate=1;
float enemy_spawnBottom=1200;
float enemy_spawnTop=2500;
int enemy_residueMax=100;
int enemy_absorbMax=3;
float enemy_recoveryInterval=3;

float enemyS_width=80;
float enemyS_height=80;
float enemyS_v=100;
float enemyS_range=1000;
int enemyS_hp=1;
int enemyS_point=5;
int enemyS_absorb=1;

float enemyL_width=120;
float enemyL_height=120;
float enemyL_v=50;
float enemyL_range=1500;
int enemyL_hp=2;
int enemyL_point=10;
int enemyL_absorb=2;

int ghost_number=25;
float ghostS_vMax=3;
float ghostL_vMax=1.5f;

int beam_number=20;
float pinch_distanceMin=1200;
float pinch_distanceMax=200;
float pinch_nearRateMax=0.05f;
int pinch_hpMax=50;
int pinch_hpMin=10;

float beamN_width=80;
float beamN_height=80;
float beamN_V=500;
int beamN_point=5;

float beamS_width=400;
float beamS_height=400;
float beamS_V=1000;
int beamS_point=25;
float beamS_hitstop=0.5f;

float fire_length=0.5f;

float get_length=0.3f;
float get_width=120;
float get_height=120;

float damage_length=1;
float damage_width=160;
float damage_height=160;
float damage_hitstop=0.1f;

float hit_length=1;
float hit_width=80;
float hit_height=80;
float hit_hitstop=0.1f;

float hp_x=100;
float hp_y=15;
float hp_width=800;
float hp_height=10;
float hp_textSize=20;
float hp_textX=50;
float hp_textY;
int hp_textColor=0xFF00FF00;

float residue_x=100;
float residue_y=35;
float residue_width=800;
float residue_height=10;
float residue_textSize=20;
float residue_textX=15;
float residue_textY;
int residue_textColor=0xFFFF0000;

float charge_textSize=24;
float charge_textX=35;
float charge_textY=60;
int charge_textColor=0xFF00FF00;

float score_textSize=24;
float score_textX=35;
float score_textY=35;
int score_textColor=0xFF00FF00;

float time_textSize=24;
float time_textX=35;
float time_textY=85;
int time_textColor=0xFF00FF00;

float pinch_x=800;
float pinch_y=35;
float pinch_width=120;
float pinch_height=20;
float pinch_textSize=24;
float pinch_textX=710;
float pinch_textY;
int pinch_colorE=0xFFFFFF00;
int pinch_colorF=0xFFFF0000;

float sign_x;
float sign_y;
float ready_width=545;
float ready_height=105;
float go_width=205;
float go_height=105;
float begin_timeMax=4;

float result_width=450;
float result_height=100;
float result_textSize=30;
float result_textX=200;
float result_textY=350;
int result_textColor=0xFF00FF00;
float finish_timeMax=1.5f;
int score_win=300;
int score_lose=300;

float horizon_height=50;
int backN_color=0xFF3A3948;
int backS_color=0xFFFF0000;
int backC_color=0xFF8BF2FF;
int backD_color=0xFF0000FF;
int pinch_tint=0xFF9B6262;
int dead_tint=0xFF63629B;
int mute=0;

float player_x;
float player_y;
float player_vx;
float player_vy;
int player_right;
int player_land;
int player_hp;
int player_satiety;
float fire_time;
float pinch_rate;

int enemy_residue;
int enemy_absorbCount;
float enemy_recoveryTime;
int beam_count;
int charge;
int score;
float time;
float beginPlayTimeMillis;
float deltaTime;
float deltaTime_unscale;
float pMillis;
float time_scale;

float damage_hitstopCount;
int damage_hitstopFlag;
float hit_hitstopCount;
int hit_hitstopFlag;
float beamS_hitstopCount;
int beamS_hitstopFlag;

int preplay;
float begin_time;
int onplay;
int postplay;
float finish_time;
int gameresult;
int pausing;

int hit_count;
int damage_count;

int readySE_flag;
int goSE_flag;

float[]item_x=new float[item_number];
float[]item_y=new float[item_number];
float[]item_width=new float[item_number];
float[]item_height=new float[item_number];
float[]item_v=new float[item_number];
int[]item_point=new int[item_number];
char[]item_type=new char[item_number];

int[]get_appear=new int[item_number];
float[]get_x=new float[item_number];
float[]get_y=new float[item_number];
float[]get_time=new float[item_number];

float[]enemy_x1=new float[enemy_number];
float[]enemy_y1=new float[enemy_number];
float[]enemy_x2=new float[enemy_number];
float[]enemy_y2=new float[enemy_number];
float[]enemy_x=new float[enemy_number];
float[]enemy_y=new float[enemy_number];
float[]enemy_width=new float[enemy_number];
float[]enemy_height=new float[enemy_number];
float[]enemy_v=new float[enemy_number];
float[]enemy_range=new float[enemy_number];
int[]enemy_hp=new int[enemy_number];
int[]enemy_point=new int[enemy_number];
float[]ghost_vMax=new float[enemy_number];
int[]enemy_collide=new int[enemy_number];
int[]enemy_absorb=new int[enemy_number];
char[]enemy_type=new char[enemy_number];

int[]damage_appear=new int[enemy_number];
float[]damage_x=new float[enemy_number];
float[]damage_y=new float[enemy_number];
float[]damage_time=new float[enemy_number];

int eg=enemy_number*ghost_number;
float[]ghost_x=new float[eg];
float[]ghost_y=new float[eg];
float[]ghost_vx=new float[eg];
float[]ghost_vy=new float[eg];
float[]ghost_rx=new float[eg];
float[]ghost_ry=new float[eg];

int[]beam_appear=new int[beam_number];
float[]beam_x=new float[beam_number];
float[]beam_y=new float[beam_number];
float[]beam_v=new float[beam_number];
float[]beam_V=new float[beam_number];
float[]beam_width=new float[beam_number];
float[]beam_height=new float[beam_number];
int[]beam_point=new int[beam_number];
int[]beam_collide=new int[beam_number];
int[]beam_special=new int[beam_number];

int[]hit_appear=new int[beam_number];
float[]hit_x=new float[beam_number];
float[]hit_y=new float[beam_number];
float[]hit_time=new float[beam_number];

public void setup() {
  /* size commented out by preprocessor */;
  /* pixelDensity commented out by preprocessor */;
  noStroke();
  rectMode(CENTER);
  imageMode(CENTER);

  stopR=loadImage("stopR.png");
  stopL=loadImage("stopL.png");
  dash1R=loadImage("dash1R.png");
  dash1L=loadImage("dash1L.png");
  dash2R=loadImage("dash2R.png");
  dash2L=loadImage("dash2L.png");
  dash3R=loadImage("dash3R.png");
  dash3L=loadImage("dash3L.png");
  dash4R=loadImage("dash4R.png");
  dash4L=loadImage("dash4L.png");
  jumpR=loadImage("jumpR.png");
  jumpL=loadImage("jumpL.png");
  fireR=loadImage("fireR.png");
  fireL=loadImage("fireL.png");
  itemS=loadImage("riceballS.png");
  itemM=loadImage("riceballM.png");
  itemL=loadImage("riceballL.png");
  enemySR=loadImage("ghostSR.png");
  enemySL=loadImage("ghostSL.png");
  enemyLR=loadImage("ghostLR.png");
  enemyLL=loadImage("ghostLL.png");
  beamR=loadImage("kiaihouR.png");
  beamL=loadImage("kiaihouL.png");
  Get=loadImage("eat.png");
  damage=loadImage("bang.png");
  hit=loadImage("hit.png");
  begin=loadImage("preplay.png");
  ready=loadImage("ready.png");
  go=loadImage("go.png");
  win=loadImage("win.png");
  lose=loadImage("lose.png");

  dash_SE=new SoundFile(this, "dash.mp3");
  jump_SE=new SoundFile(this, "jump.mp3");
  land_SE=new SoundFile(this, "land.mp3");
  fire_SE=new SoundFile(this, "kiaihou.mp3");
  get_SE=new SoundFile(this, "eat.mp3");
  damage_SE=new SoundFile(this, "damage.mp3");
  hit_SE=new SoundFile(this, "hit.mp3");
  pinch_SE=new SoundFile(this, "ドーン.mp3");
  ready_SE=new SoundFile(this, "ready.mp3");
  go_SE=new SoundFile(this, "go.mp3");
  win_SE=new SoundFile(this, "win.mp3");
  lose_SE=new SoundFile(this, "lose.mp3");

  player_x=width/2;
  player_y=height-horizon_height-player_height/2;
  player_vx=0;
  player_vy=0;
  player_right=1;
  player_land=1;
  player_hp=player_hpMax;
  player_satiety=0;
  fire_time=fire_length;
  pinch_rate=0;

  sign_x=width/2;
  sign_y=height/2;

  enemy_residue=enemy_residueMax;
  enemy_absorbCount=0;
  beam_count=0;
  charge=0;
  score=0;
  time=0;
  deltaTime=0;
  deltaTime_unscale=0;
  pMillis=millis();
  time_scale=1;
  damage_hitstopCount=0;
  damage_hitstopFlag=0;
  hit_hitstopCount=0;
  hit_hitstopFlag=0;
  beamS_hitstopCount=0;
  beamS_hitstopFlag=0;

  preplay=1;
  begin_time=0;
  onplay=0;
  postplay=0;
  finish_time=0;
  pausing=0;

  hit_count=0;
  damage_count=0;

  readySE_flag=0;
  goSE_flag=0;

  for (int i=0; i<item_number; i++) {
    item_spawn(i);
    get_appear[i]=0;
  }

  for (int i=0; i<enemy_number; i++) {
    damage_appear[i]=0;
    enemy_spawn(i);
  }

  for (int i=0; i<beam_number; i++) {
    beam_appear[i]=0;
    hit_appear[i]=0;
  }
}

public void draw() {
  time();
  begin();
  active();
  finish();
}

public void begin() {
  if (preplay==1) {
    if (mousePressed || begin_time>0) {
      back();
      horizon();
      player();
      display();
      begin_time+=deltaTime_unscale;
      if (readySE_flag==0) {
        if (mute!=1)
          ready_SE.play();
        readySE_flag=1;
      }
      if (begin_time>=(begin_timeMax/2) && goSE_flag==0) {
        if (mute!=1)
          go_SE.play();
        goSE_flag=1;
      }
      if (begin_time>begin_timeMax) {
        preplay=0;
        beginPlayTimeMillis=millis();
        onplay=1;
      } else if (begin_time>begin_timeMax/2) {
        image(go, sign_x, sign_y, go_width, go_height);
      } else {
        image(ready, sign_x, sign_y, ready_width, ready_height);
      }
    } else {
      background(0);
      int wid=begin.height*width/begin.width;
      image(begin, width/2, height/2, wid, height);
    }
  }
}

public void active() {
  if (onplay==1) {
    item();
    operate();
    enemy();
    beam();
    item_collision();
    enemy_collision();
    beam_collision();
    hitstop();
    empty();
    gameover();
    gameclear();
    draw_methods();
    pause();
  }
}

public void draw_methods() {
  back();
  item_draw();
  horizon();
  player();
  enemy_draw();
  beam_draw();
  get_effect();
  damage_effect();
  hit_effect();
  display();
}

public void time() {
  if (onplay==1)time=(millis()-beginPlayTimeMillis)*0.001f;
  int m=millis();
  deltaTime_unscale=(m-pMillis)*0.001f;
  deltaTime=deltaTime_unscale*time_scale;
  pMillis=m;
}

public void back() {
  int back_color=backN_color;
  if (postplay==1) {
    if (gameresult==0) {
      back_color=backD_color;
      tint(dead_tint);
    } else {
      back_color=backC_color;
    }
  } else if (beamS_hitstopFlag==1) {
    back_color=backS_color;
    tint(pinch_tint);
  }
  background(back_color);
}

public void item() {
  for (int i=0; i<item_number; i++) {
    item_y[i]+=item_v[i]*deltaTime;
    if (item_y[i]>height-horizon_height+item_height[i]) {
      item_spawn(i);
    }
  }
}

public void item_draw() {
  for (int i=0; i<item_number; i++) {
    switch(item_type[i]) {
    case 'S':
      image(itemS, item_x[i], item_y[i], item_width[i], item_height[i]);
    case 'M':
      image(itemM, item_x[i], item_y[i], item_width[i], item_height[i]);
    case 'L':
      image(itemL, item_x[i], item_y[i], item_width[i], item_height[i]);
      break;
    default:
      println("item_type : NULL");
      break;
    }
  }
}

public void horizon() {
  fill(188, 154, 112);
  rect(width/2, height-horizon_height/2, width, horizon_height);
}

public void player() {
  if (player_right==1) {
    if (fire_time<fire_length) {
      image(fireR, player_x, player_y, player_width, player_height);
      fire_time+=deltaTime;
    } else if (player_y<height-horizon_height-player_height/2) {
      image(jumpR, player_x, player_y, player_width, player_height);
    } else if (onplay==1 && keyPressed && keyCode==RIGHT) {
      int t=floor(time*4/player_dash)%4;
      if (t==0) {
        image(dash1R, player_x, player_y, player_width, player_height);
      } else if (t==1) {
        image(dash2R, player_x, player_y, player_width, player_height);
      } else if (t==2) {
        image(dash3R, player_x, player_y, player_width, player_height);
      } else {
        image(dash4R, player_x, player_y, player_width, player_height);
      }
    } else {
      image(stopR, player_x, player_y, player_width, player_height);
    }
  } else {
    if (fire_time<fire_length) {
      image(fireL, player_x, player_y, player_width, player_height);
      fire_time+=deltaTime;
    } else if (player_y<height-horizon_height-player_height/2) {
      image(jumpL, player_x, player_y, player_width, player_height);
    } else if (onplay==1 && keyPressed && keyCode==LEFT) {
      int t=floor(time*4/player_dash)%4;
      if (t==0) {
        image(dash1L, player_x, player_y, player_width, player_height);
      } else if (t==1) {
        image(dash2L, player_x, player_y, player_width, player_height);
      } else if (t==2) {
        image(dash3L, player_x, player_y, player_width, player_height);
      } else {
        image(dash4L, player_x, player_y, player_width, player_height);
      }
    } else {
      image(stopL, player_x, player_y, player_width, player_height);
    }
  }
}

public void operate() {
  if (keyPressed && key==CODED && time_scale>0) {
    switch(keyCode) {
    case RIGHT:
      player_vx+=player_ax*deltaTime;
      if (player_vx>player_vxMax) {
        player_vx=player_vxMax;
      }
      player_right=1;
      fire_time=fire_length;
      int tr=floor(time*4/player_dash)%2;
      if (tr==0 && player_y==height-horizon_height-player_height/2) {
        if (mute!=1)
          dash_SE.play();
      }
      break;
    case LEFT:
      player_vx-=player_ax*deltaTime;
      if (player_vx<-player_vxMax) {
        player_vx=-player_vxMax;
      }
      player_right=0;
      fire_time=fire_length;
      int tl=floor(time*4/player_dash)%2;
      if (tl==0 && player_y==height-horizon_height-player_height/2) {
        if (mute!=1)
          dash_SE.play();
      }
      break;
    default:
      break;
    }
  } else {
    if (player_vx>player_ax*deltaTime) {
      player_vx-=player_ax*deltaTime;
    } else if (player_vx<-player_ax*deltaTime) {
      player_vx+=player_ax*deltaTime;
    } else {
      player_vx=0;
    }
  }

  player_x+=player_vx*deltaTime;

  player_vy-=player_ay*deltaTime;
  player_y-=player_vy*deltaTime;

  if (player_x<player_width/2) {
    player_x=player_width/2;
    player_vx=0;
  }
  if (player_x>width-player_width/2) {
    player_x=width-player_width/2;
    player_vx=0;
  }
  if (player_y>height-horizon_height-player_height/2) {
    player_y=height-horizon_height-player_height/2;
    player_vy=0;
    fire_time=fire_length;
    if (player_land==0) {
      if (mute!=1)
        land_SE.play();
      player_land=1;
    }
  }
}

public void enemy() {
  for (int i=0; i<enemy_number; i++) {
    float dx=enemy_x[i]-player_x;
    float dy=enemy_y[i]-player_y;
    enemy_x1[i]-=enemy_v[i]*dx/sqrt(dx*dx+dy*dy)*deltaTime;
    enemy_y1[i]-=enemy_v[i]*dy/sqrt(dx*dx+dy*dy)*deltaTime;

    enemy_x2[i]=0;
    enemy_y2[i]=0;
    for (int j=0; j<ghost_number; j++) {
      int n=i*ghost_number+j;
      ghost_x[n]+=ghost_vx[n]*deltaTime;
      ghost_y[n]+=ghost_vy[n]*deltaTime;
      enemy_x2[i]+=ghost_rx[n]*sin(ghost_x[n]*ghost_vMax[i]);
      enemy_y2[i]+=ghost_ry[n]*sin(ghost_y[n]*ghost_vMax[i]);
    }
    enemy_x2[i]*=enemy_range[i]/ghost_number;
    enemy_y2[i]*=enemy_range[i]/ghost_number;

    enemy_x[i]=enemy_x1[i]+enemy_x2[i];
    enemy_y[i]=enemy_y1[i]+enemy_y2[i];
  }

  enemy_recoveryTime+=deltaTime;
  while (enemy_recoveryTime>=enemy_recoveryInterval) {
    enemy_recoveryTime-=enemy_recoveryInterval;
    enemy_residue++;
  }
}

public void enemy_draw() {
  if (onplay==0 && gameresult==1)return;
  for (int i=0; i<enemy_number; i++) {
    if (enemy_x[i]<player_x) {
      switch(enemy_type[i]) {
      case 'S':
        image(enemySR, enemy_x[i], enemy_y[i], enemy_width[i], enemy_height[i]);
      case 'L':
        image(enemyLR, enemy_x[i], enemy_y[i], enemy_width[i], enemy_height[i]);
        break;
      default:
        println("enemy_type : NULL");
      }
    } else {
      switch(enemy_type[i]) {
      case 'S':
        image(enemySL, enemy_x[i], enemy_y[i], enemy_width[i], enemy_height[i]);
      case 'L':
        image(enemyLL, enemy_x[i], enemy_y[i], enemy_width[i], enemy_height[i]);
        break;
      default:
        println("enemy_type : NULL");
      }
    }
  }
}

public void beam() {
  for (int i=0; i<beam_number; i++) {
    if (beam_appear[i]==1) {
      beam_x[i]+=beam_v[i]*deltaTime;
    }
    if (beam_x[i]<-beam_width[i] || beam_x[i]>width+beam_width[i]) {
      beam_appear[i]=0;
    }
  }
}

public void beam_draw() {
  if (beamS_hitstopFlag==1 || postplay==1)tint(255);
  for (int i=0; i<beam_number; i++) {
    if (beam_appear[i]==1) {
      if (beam_v[i]>0) {
        image(beamR, beam_x[i], beam_y[i], beam_width[i], beam_height[i]);
      } else {
        image(beamL, beam_x[i], beam_y[i], beam_width[i], beam_height[i]);
      }
    }
  }
}

public void hitstop() {
  if (time_scale>0)return;
  if (damage_hitstopFlag==1) {
    damage_hitstopCount+=deltaTime_unscale;
    if (damage_hitstopCount>=damage_hitstop) {
      damage_hitstopCount=0;
      damage_hitstopFlag=0;
    }
  }
  if (hit_hitstopFlag==1) {
    hit_hitstopCount+=deltaTime_unscale;
    if (hit_hitstopCount>=hit_hitstop) {
      hit_hitstopCount=0;
      hit_hitstopFlag=0;
    }
  }
  if (beamS_hitstopFlag==1) {
    beamS_hitstopCount+=deltaTime_unscale;
    if (beamS_hitstopCount>=beamS_hitstop) {
      beamS_hitstopCount=0;
      beamS_hitstopFlag=0;
    }
  }
  if (damage_hitstopFlag==0
    && hit_hitstopFlag==0
    && beamS_hitstopFlag==0
    && pausing==0) {
    time_scale=1;
  }
}

public void item_collision() {
  for (int i=0; i<item_number; i++) {
    float dx=abs(player_x-item_x[i]);
    float dy=abs(player_y-item_y[i]);
    if (dx<(player_width+item_width[i])/2 && dy<(player_height+item_height[i])/2) {
      item_get(i);
    }
  }
}

public void item_get(int i) {
  charge+=item_point[i];
  score+=item_point[i];
  player_satiety+=item_point[i];
  while (player_satiety>=player_satietyMax) {
    player_satiety-=player_satietyMax;
    player_hp++;
  }
  get_appear[i]=1;
  get_x[i]=player_x;
  get_y[i]=player_y-player_height/2;
  get_time[i]=0;
  if (mute!=1)
    get_SE.play();
  item_spawn(i);
}

public void enemy_collision() {
  if (time_scale==0)return;
  for (int i=0; i<enemy_number; i++) {
    if (enemy_collide[i]==1)enemy_spawn(i);
    else {
      float dx=abs(enemy_x[i]-player_x);
      float dy=abs(enemy_y[i]-player_y);
      if (dx<(enemy_width[i]+player_width)/2 && dy<(enemy_height[i]+player_height)/2) {
        damage(i);
      }
    }
  }
}

public void damage(int i) {
  player_hp-=enemy_point[i];
  charge-=enemy_point[i];
  score-=enemy_point[i];
  damage_count++;
  damage_appear[i]=1;
  damage_x[i]=(enemy_x[i]+player_x)/2;
  damage_y[i]=(enemy_y[i]+player_y)/2;
  damage_time[i]=0;
  damage_hitstopFlag=1;
  time_scale=0;
  if (mute!=1)
    damage_SE.play();
  enemy_absorbCount+=enemy_absorb[i];
  while (enemy_absorbCount>=enemy_absorbMax) {
    enemy_absorbCount-=enemy_absorbMax;
    enemy_residue++;
  }
  enemy_collide[i]=1;
  pinch();
}

public void beam_collision() {
  if (time_scale==0)return;
  for (int i=0; i<beam_number; i++) {
    if (beam_collide[i]==1) {
      beam_appear[i]=0;
      beam_collide[i]=0;
      continue;
    }
    for (int j=0; j<enemy_number; j++) {
      float dx=abs(beam_x[i]-enemy_x[j]);
      float dy=abs(beam_y[i]-enemy_y[j]);
      if (beam_appear[i]==1) {
        if (dx<(beam_width[i]+enemy_width[j])/2 && dy<(beam_height[i]+enemy_height[j])/2
          && enemy_collide[j]==0) {
          hit(i, j);
          if (beam_special[i]==0)break;
        }
      }
    }
  }
}

public void hit(int i, int j) {
  if (beam_special[i]==0) {
    beam_collide[i]=1;
    hit_hitstopFlag=1;
    time_scale=0;
  }
  score+=enemy_point[j];
  enemy_hp[j]--;
  player_hp+=player_hpAbsorb;
  hit_count++;
  hit_appear[i]=1;
  hit_x[i]=enemy_x[j];
  hit_y[i]=enemy_y[j];
  hit_time[i]=0;
  if (enemy_type[j]=='L' && beam_special[i]==1) {
    enemy_hp[j]=0;
    player_hp+=player_hpAbsorb;
  }
  if (mute!=1)
    hit_SE.play();
  if (enemy_hp[j]==0) {
    enemy_residue--;
    enemy_collide[j]=1;
  }
  if (enemy_type[j]=='L' && enemy_hp[j]==1) {
    enemy_width[j]=enemyS_width;
    enemy_height[j]=enemyS_height;
    enemy_range[j]=enemyS_range;
    enemy_point[j]=enemyS_point;
  }
}

public void get_effect() {
  for (int i=0; i<item_number; i++) {
    if (get_appear[i]==1) {
      image(Get, get_x[i], get_y[i], get_width, get_height);
      get_time[i]+=deltaTime;
      if (get_time[i]>=get_length) {
        get_appear[i]=0;
      }
    }
  }
}

public void damage_effect() {
  for (int i=0; i<enemy_number; i++) {
    if (damage_appear[i]==1) {
      image(damage, damage_x[i], damage_y[i], damage_width, damage_height);
      damage_time[i]+=deltaTime;
      if (damage_time[i]>=damage_length) {
        damage_appear[i]=0;
      }
    }
  }
}

public void hit_effect() {
  for (int i=0; i<beam_number; i++) {
    if (hit_appear[i]==1) {
      image(hit, hit_x[i], hit_y[i], hit_width, hit_height);
      hit_time[i]+=deltaTime;
      if (hit_time[i]>=hit_length) {
        hit_appear[i]=0;
      }
    }
  }
}

public void empty() {
  if (charge<0) {
    charge=0;
  }
  if (player_hp<0) {
    player_hp=0;
  } else if (player_hp>player_hpMax) {
    player_hp=player_hpMax;
  }
  if (enemy_residue>enemy_residueMax) {
    enemy_residue=enemy_residueMax;
  }
}

public void display() {
  fill(hp_textColor);
  float l=hp_width*player_hp/player_hpMax;
  float x=hp_x+l/2;
  float y=hp_y+height-horizon_height;
  rect(x, y, l, hp_height);
  hp_textY=y+hp_height/2;
  textSize(hp_textSize);
  text("HP : ", hp_textX, hp_textY);

  fill(residue_textColor);
  l=hp_width*enemy_residue/enemy_residueMax;
  x=residue_x+l/2;
  y=residue_y+height-horizon_height;
  rect(x, y, l, residue_height);
  residue_textY=y+residue_height/2;
  textSize(residue_textSize);
  text("ENEMY : ", residue_textX, residue_textY);

  fill(charge_textColor);
  textSize(charge_textSize);
  text("CHARGE : "+charge, charge_textX, charge_textY);

  fill(score_textColor);
  textSize(score_textSize);
  text("SCORE : "+score, score_textX, score_textY);

  fill(time_textColor);
  textSize(time_textSize);
  text("TIME : "+floor(time), time_textX, time_textY);

  pinch_textY=pinch_y+pinch_height/2;
  if (beamS_hitstopFlag==1) fill(255);
  else fill(pinch_colorE);
  x=pinch_x+pinch_width/2;
  rect(x, pinch_y, pinch_width, pinch_height);
  textSize(pinch_textSize);
  text("PINCH : ", pinch_textX, pinch_textY);
  if (pinch_rate>0 && beamS_hitstopFlag==0) {
    l=pinch_width*pinch_rate;
    x=pinch_x+l/2;
    fill(pinch_colorF);
    rect(x, pinch_y, l, pinch_height);
  }
}

public void gameover() {
  if (player_hp<=0) {
    onplay=0;
    postplay=1;
    if (mute!=1)
      lose_SE.play();
    gameresult=0;
  }
}

public void gameclear() {
  if (enemy_residue<=0) {
    onplay=0;
    postplay=1;
    if (mute!=1)
      win_SE.play();
    gameresult=1;
  }
}

public void finish() {
  if (postplay==1) {
    finish_time+=deltaTime_unscale;
    if (finish_time>finish_timeMax) {
      background(0);
      if (gameresult==1) {
        score+=score_win;
        int wid=width*win.height/win.width;
        image(win, width/2, height/2, wid, height);
      } else {
        score-=score_lose;
        int wid=width*lose.height/lose.width;
        image(lose, width/2, height/2, wid, height);
      }

      fill(result_textColor);
      textSize(result_textSize);
      text("SCORE : "+score, result_textX, result_textY);
      text("DEFEATED : "+hit_count, result_textX, result_textY+result_textSize);
      text("DAMAGED : "+damage_count, result_textX, result_textY+result_textSize*2);
      text("TIME : "+floor(time), result_textX, result_textY+result_textSize*3);

      noLoop();
    }
  }
}

public void pause() {
  if (pausing==1) {
    time_scale=0;
  }
}

public void item_spawn(int n) {
  float u=itemS_rate+itemM_rate+itemL_rate;
  float dice=random(u);
  if (dice<itemS_rate) {
    item_type[n]='S';
  } else if (dice<itemS_rate+itemM_rate) {
    item_type[n]='M';
  } else {
    item_type[n]='L';
  }
  switch(item_type[n]) {
  case 'S':
    item_width[n]=itemS_width;
    item_height[n]=itemS_height;
    item_v[n]=itemS_v;
    item_point[n]=itemS_point;
    break;
  case 'M':
    item_width[n]=itemM_width;
    item_height[n]=itemM_height;
    item_v[n]=itemM_v;
    item_point[n]=itemM_point;
    break;
  case 'L':
    item_width[n]=itemL_width;
    item_height[n]=itemL_height;
    item_v[n]=itemL_v;
    item_point[n]=itemL_point;
    break;
  default:
    println("item_type : NULL");
    break;
  }
  item_x[n]=random(item_width[n], width-item_width[n]);
  item_y[n]=random(-item_height[n]-height, -item_height[n]);
}

public void enemy_spawn(int n) {
  for (int i=0; i<ghost_number; i++) {
    int N=n*ghost_number+i;
    ghost_x[N]=0;
    ghost_vx[N]=random(-1, 1);
    ghost_rx[N]=random(1);
    ghost_y[N]=0;
    ghost_vy[N]=random(-1, 1);
    ghost_ry[N]=random(1);
  }
  float theta=random(PI);
  float d=random(enemy_spawnBottom, enemy_spawnTop);
  enemy_x1[n]=player_x+d*cos(theta);
  enemy_y1[n]=player_y-d*sin(theta);
  enemy_x2[n]=0;
  enemy_y2[n]=0;
  enemy_x[n]=enemy_x1[n];
  enemy_y[n]=enemy_y1[n];
  float u=enemyS_rate+enemyL_rate;
  float dice=random(u);
  if (dice<enemyS_rate) {
    enemy_type[n]='S';
  } else {
    enemy_type[n]='L';
  }
  switch(enemy_type[n]) {
  case 'S':
    enemy_width[n]=enemyS_width;
    enemy_height[n]=enemyS_height;
    enemy_v[n]=enemyS_v;
    enemy_range[n]=enemyS_range;
    enemy_hp[n]=enemyS_hp;
    enemy_point[n]=enemyS_point;
    enemy_absorb[n]=enemyS_absorb;
    ghost_vMax[n]=ghostS_vMax;
    break;
  case 'L':
    enemy_width[n]=enemyL_width;
    enemy_height[n]=enemyL_height;
    enemy_v[n]=enemyL_v;
    enemy_range[n]=enemyL_range;
    enemy_hp[n]=enemyL_hp;
    enemy_point[n]=enemyL_point;
    enemy_absorb[n]=enemyL_absorb;
    ghost_vMax[n]=ghostL_vMax;
    break;
  default:
    println("enemy_type : NULL");
    break;
  }
  enemy_collide[n]=0;
}

public void keyPressed() {
  if (keyCode==ENTER)switch_pausing();
  if (time_scale>0) {
    if (keyCode==UP)jump();
    if (key=='a')fire();
  }
}

public void jump() {
  if (onplay==1 && player_y==height-horizon_height-player_height/2) {
    player_vy=player_vyMax;
    fire_time=fire_length;
    if (mute!=1)
      jump_SE.play();
    player_land=0;
  }
}

public void fire() {
  beam_special[beam_count]=0;
  beam_width[beam_count]=beamN_width;
  beam_height[beam_count]=beamN_height;
  beam_V[beam_count]=beamN_V;
  beam_point[beam_count]=beamN_point;
  if (pinch()==1) {
    beam_special[beam_count]=1;
    beam_width[beam_count]=beamS_width;
    beam_height[beam_count]=beamS_height;
    beam_V[beam_count]=beamS_V;
    beam_point[beam_count]=charge;
    pinch_rate=0;
  }

  if (charge>=beam_point[beam_count]) {
    charge-=beam_point[beam_count];
    beam_appear[beam_count]=1;
    fire_time=0;
    if (mute!=1)
      fire_SE.play();
    if (player_right==1) {
      beam_x[beam_count]=player_x+(beam_width[beam_count]+player_width)/2;
      beam_v[beam_count]=beam_V[beam_count];
    } else {
      beam_x[beam_count]=player_x-(beam_width[beam_count]+player_width)/2;
      beam_v[beam_count]=-beam_V[beam_count];
    }
    beam_y[beam_count]=player_y;
    beam_v[beam_count]+=player_vx;
    if (beam_special[beam_count]==1) {
      pinch_SE.play();
      beamS_hitstopFlag=1;
      time_scale=0;
    }
    beam_count++;
    if (beam_count==beam_number) {
      beam_count=0;
    }
  }
}

public void switch_pausing() {
  if (pausing==0) {
    pausing=1;
  } else {
    pausing=0;
  }
}

public int pinch() {
  if (charge<beamN_point) {
    return 0;
  }
  if (pinch_rate>0)pinch_rate=0;
  if (player_hp>=pinch_hpMax) {
    return 0;
  }
  if (charge>=beamS_point) {
    return 0;
  }
  if (player_hp*enemy_residueMax>=player_hpMax*enemy_residue) {
    return 0;
  }

  float nearRate=0;
  float hpRate=0;
  float chargeRate=0;

  for (int i=0; i<enemy_number; i++) {
    float dx=player_x-enemy_x[i];
    float dy=player_y-enemy_y[i];
    float dd=dx*dx+dy*dy;
    if (dd<=pinch_distanceMin*pinch_distanceMin) {
      nearRate+=pinch_nearRateMax;
    } else if (dd<pinch_distanceMax*pinch_distanceMax) {
      float d=sqrt(dd);
      nearRate+=pinch_nearRateMax*(1f-(d-pinch_distanceMin)/(pinch_distanceMax-pinch_distanceMin));
    }
  }

  if (player_hp<pinch_hpMin)hpRate=1;
  else {
    float hpDiff=player_hp-pinch_hpMin;
    hpRate=1f-hpDiff/(pinch_hpMax-pinch_hpMin);
  }

  float chargeDiff=charge-beamN_point;
  chargeRate=1f-chargeDiff/(beamS_point-beamN_point);

  float rate=nearRate*hpRate*chargeRate;

  float rand=random(0f, 1f);
  int result=0;
  pinch_rate=rate/rand;
  if (rand<=rate) {
    result=1;
    pinch_rate=1;
  }
  return result;
}


  public void settings() { size(960, 540);
pixelDensity(1); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "ghosdo" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
